# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.network :private_network, ip: "192.168.35.15"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--name", "Example2UP", "--memory", "1024"]
  end

  # Shared folder from the host machine to the guest machine. Uncomment the line
  # below to enable it.
  config.vm.synced_folder ".", "/vagrant", type: "nfs"

  # Ansible provisioner.
  config.vm.provision "ansible" do |ansible|
    ansible.inventory_path = "hosts/hosts"
    ansible.limit = "all"
    ansible.playbook = "playbook.yml"
    ansible.host_key_checking = false
    ansible.verbose = "vvvv"
  end
end
